[profile.release]
overflow-checks = true

[workspace]
resolver = "2"
members = ["crates/air", "crates/transcript", "crates/commitment", "crates/fri", "crates/pow", "crates/stark"]
exclude = []

[workspace.package]
description = ""
edition = "2021"
homepage = ""
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/iosis-tech/cairovm-verifier"
version = "0.0.1"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
starknet-crypto = "0.7.1"
starknet-core = "0.11.1"
thiserror = "1.0.61"
serde_with = "2.3.2"
sha3 = "0.10.8"
starknet-types-core = "0.1.5"

cairovm_verifier_air = { path = "crates/air" }
cairovm_verifier_transcript = { path = "crates/transcript" }
cairovm_verifier_commitment = { path = "crates/commitment" }
cairovm_verifier_fri = { path = "crates/fri" }
cairovm_verifier_pow = { path = "crates/pow" }
cairovm_verifier_stark = { path = "crates/stark" }
